stages:
  # - documentation
  - test

variables:
  PYTHON_VERSION: "3.12"

before_script:
  - apt-get update -qq
  - apt update && apt install -y build-essential libgdal-dev
  - apt-get install -y pandoc
  - python3 -m pip install .

# documentation:
#   stage: documentation
#   image: python:${PYTHON_VERSION}
#   script:
#     - cd docs
#     - make html  # Or whatever command you use to build your documentation
#   artifacts:
#     paths:
#       - docs/_build/html  # Adjust this path according to your documentation build output

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - pytest tests

