# conda env create|update -f environment.yml
name: sensarp-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6*
  - sphinxcontrib-bibtex>=0.4 # docs
  - pytest>=4.6 # testing
  - jupyter
  - matplotlib
  - scipy
  - future
  - numba
  - numpy>=1.18,<1.24

