# conda env create|update -f environment.yml
name: SenSE

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10*
  - sphinxcontrib-bibtex>=0.4 # docs
  - pytest>=4.6 # testing
  - jupyter
  - matplotlib
  - scipy
  - future
  - numba
  - numpy
  - anyio==3.*

