name: Convert README from RST to Markdown

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'README.rst'

  jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: dev  # Checkout the dev branch

      - name: Create new branch
        run: git checkout -b update-readme-${{ github.run_id }}

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert README.rst to README.md
        run: pandoc README.rst -f rst -t markdown -o README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Convert README.rst to README.md"
          git push origin update-readme-${{ github.run_id }}

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-readme-${{ github.run_id }}
          title: "Update README.md from README.rst"
          body: "Automatically generated by GitHub Actions."
          base: dev  # Target branch to merge changes