name: Convert README from RST to Markdown

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'README.rst'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Convert README.rst to README.md
      run: pandoc README.rst -f rst -t markdown -o README.md

    - name: Commit converted README.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Convert README.rst to README.md"